fix: github action flow

diff --git a/.github/workflows/paymattic.upload.yml b/.github/workflows/paymattic.upload.yml
--- a/.github/workflows/paymattic.upload.yml
+++ b/.github/workflows/paymattic.upload.yml
@@ -7,48 +7,69 @@ on:
 
 jobs:
   deploy:
-    name: Upload Files
+    name: Upload files
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout GitHub repository
+      - name: Checkout Git repo
         uses: actions/checkout@v3
 
-      - name: Prepare and Sync Files
-        env:
-          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
-          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
+      - name: Extract version from tag
+        id: vars
         run: |
-          sudo apt-get update && sudo apt-get install -y subversion
-          svn checkout "https://plugins.svn.wordpress.org/chip-for-paymattic/" svn \
-            --username "${SVN_USERNAME}" \
-            --password "${SVN_PASSWORD}" \
-            --non-interactive --trust-server-cert
-          mkdir deploy
+          TAG=${GITHUB_REF##*/}
+          VERSION=${TAG#paymattic-upload-v}
+          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
+
+      - name: Create new version folder
+        run: |
+          VERSION="${{ steps.vars.outputs.version }}"
+          mkdir "$VERSION"
           shopt -s extglob
-          cp -r !(deploy|.git|.github|svn) deploy/
-          rsync -avc --delete --exclude=".svn" ./deploy/ ./svn/trunk/
+          EXCLUDE_PATTERN="!(${VERSION}|composer.json|README.md|package.json|.*)"
+          eval mv $EXCLUDE_PATTERN "$VERSION"
 
-      - name: Files Changes
+      - name: Install SVN
+        run: sudo apt-get install -y subversion
+
+      - name: Checkout SVN
         run: |
-          cd svn/trunk
-          svn status | grep '^?' | cut -c9- | xargs -d '\n' -r svn add
-          svn status | grep '^M' || echo "No modified files"
-          svn status | grep '^!' | cut -c9- | xargs -d '\n' -r svn delete
+          svn checkout --username "$SVN_USERNAME" --password "$SVN_PASSWORD" --non-interactive --trust-server-cert https://plugins.svn.wordpress.org/chip-for-paymattic/ svn-tags
 
-      - name: Upload Files to SVN
+      - name: Check for version conflict
+        run: |
+          VERSION="${{ steps.vars.outputs.version }}"
+          if [ -d "svn-tags/tags/$VERSION" ]; then
+            echo "❌ The tag '$VERSION' already exists in SVN. Aborting."
+            exit 1
+          fi
+
+      - name: Copy new version folder into tags folder
+        run: |
+          VERSION="${{ steps.vars.outputs.version }}"
+          cp -R "$VERSION" "svn-tags/tags"
+
+      - name: Track new version folder
+        run: |
+          VERSION="${{ steps.vars.outputs.version }}"
+          cd svn-tags/tags
+          svn add "$VERSION"
+
+      - name: List file changes
+        run: |
+          cd svn-tags
+          echo "SVN status:"
+          svn status
+
+      - name: Commit changes to SVN
         env:
           SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
           SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
         run: |
-          cd svn
-          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
+          COMMIT_MSG=$(git log -1 --pretty=%B)
 
-          if [[ -n "$(svn status)" ]]; then
-            svn commit -m "$COMMIT_MESSAGE" \
-              --username "${SVN_USERNAME}" \
-              --password "${SVN_PASSWORD}" \
-              --non-interactive --trust-server-cert
-          else
-            echo "No changes to commit."
-          fi
+          cd svn-tags
+          svn commit -m "$COMMIT_MSG" \
+            --username "$SVN_USERNAME" \
+            --password "$SVN_PASSWORD" \
+            --non-interactive --trust-server-cert
